version: '3.3'
services:
  pg:
    image: 'postgres'
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car_service
volumes:
  pg: