spring:
  flyway:
    locations: classpath:db/migration
    outOfOrder: true
  datasource:
    url: jdbc:postgresql://localhost:5434/car_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: INFO